### ISSUE TITLE
Fix Local Testnet Support

### ISSUE THREAD

**Issue by wpank** [paritytech/ledgeracio#30]
When running a local Polkadot testnet (based on v0.8.22 - Polkadot runtime 22), the following behavior occurs:

A local testnet is run with 3 nodes - the main node is run with the following command:
```
polkadot --chain=polkadot-local --validator --unsafe-ws-external --rpc-methods=Unsafe --rpc-external=True --ws-port 9946 --rpc-port 9935 --rpc-cors all --pruning archive --alice --node-key aa788920201122290fc7d3faf00698d9a8e061d7173424da2a31a8130a882a5f
```

Then running Ledgeracio with the following command:
```bash
 ./target/release/ledgeracio  -h http://127.0.0.1:9935 --network polkadot validator status   
```

This causes the terminal to hang (no error is printed, nothing is returned, the process doesn't stop).

Ive gotten the address of the first index and set that as an active controller for a validator in the network, so I would assume the status command should return something.

I'm going to assume this means that local testnets are not supported, or I'm using this wrong.

**Comment by DemiMarie** [comment]
Thanks for the bug report!

Local testnets should be supported, so this is a release-blocking bug.  I will fix this.

**Comment by DemiMarie** [comment]
I believe that there are two bugs here:

1. If I run `polkadot --dev=kusama --no-telemetry --rpc-methods=unsafe --unsafe-ws-external` in one terminal and run `curl --data-raw '{"jsonrpc":"2.0","id":1,"method":"system_properties","params":null}' -H 'Content-Type: application/json' -- http://localhost:9933` in another, the response is `{"jsonrpc":"2.0","result":{},"id":1}`, which I think is wrong.  A working chain must have at least a token name.
2. `substrate-subxt` handles decoding errors incorrectly, most likely due to a bug in the `jsonrpsee` crate.

**Comment by DemiMarie** [comment]
Fixed by https://github.com/DemiMarie/substrate-subxt/commit/3efe16f2ff4ad7924b33b5982448313a55e6bc79 and https://github.com/paritytech/ledgeracio/commit/1fe4bd7b95cd9596edc88c1d191a4bf3593006ca
